"""
AI DJ ML Sidecar — FastAPI server.
Binds to 127.0.0.1:7433 only (local-only enforcement, SOC2 Rule 2).
Authenticates requests with X-API-Key header (generated by Electron on startup).
"""
import os
import secrets
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, Security, BackgroundTasks
from fastapi.security import APIKeyHeader
from pydantic import BaseModel
import uvicorn

# Import analysis modules (graceful failure handled inside each)
from features import extract_features
from genre_infer import infer_genre, resolve_model, MACRO_ONNX, MACRO_PT
from mood import classify_mood, is_model_loaded as mood_loaded
from embeddings import generate_embedding, is_model_loaded as embed_loaded
from fingerprint import generate_fingerprint
from stems import separate_stems_async, get_job_status, cleanup_old_jobs

# ─── API Key Auth ────────────────────────────────────────────────

EXPECTED_KEY = os.environ.get("AIDJ_ML_KEY", "")
api_key_header = APIKeyHeader(name="X-API-Key", auto_error=True)


def require_api_key(key: str = Security(api_key_header)) -> str:
    if not EXPECTED_KEY:
        raise HTTPException(status_code=500, detail="Server misconfigured: no API key set")
    if not secrets.compare_digest(key, EXPECTED_KEY):
        raise HTTPException(status_code=401, detail="Invalid API key")
    return key


# ─── Schemas ─────────────────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    file_path: str


class StemRequest(BaseModel):
    file_path: str
    output_dir: str


class AnalyzeResponse(BaseModel):
    features: dict
    genre: dict
    mood: dict
    embedding: list
    fingerprint: str


class HealthResponse(BaseModel):
    status: str
    models: dict


# ─── Lifespan ────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("[ML Sidecar] Starting up…")
    yield
    print("[ML Sidecar] Shutting down.")
    cleanup_old_jobs()


# ─── App ─────────────────────────────────────────────────────────

app = FastAPI(
    title="AI DJ ML Sidecar",
    version="1.0.0",
    docs_url=None,    # Disable Swagger UI in production
    redoc_url=None,
    lifespan=lifespan,
)


@app.get("/health", response_model=HealthResponse)
async def health(_: str = Security(require_api_key)):
    """Health check — returns model availability."""
    
    macro_path, macro_backend = resolve_model(MACRO_ONNX, MACRO_PT)
    genre_status = macro_backend if macro_path else "heuristic"
    
    return {
        "status": "ok",
        "models": {
            "genre": genre_status,
            "mood": "onnx" if mood_loaded() else "heuristic",
            "embedding": "onnx" if embed_loaded() else "spectral",
        }
    }


@app.post("/analyze", response_model=AnalyzeResponse)
async def analyze_track(
    req: AnalyzeRequest,
    _: str = Security(require_api_key)
):
    """
    Full audio analysis pipeline.
    Returns features, genre, mood, embedding, fingerprint.
    SOC2 Rule 2: file_path must be local; we never upload audio bytes.
    """
    # Basic path security check
    file_path = os.path.normpath(req.file_path)
    if not os.path.isabs(file_path):
        raise HTTPException(status_code=400, detail="file_path must be absolute")
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail=f"File not found: {file_path}")
        
    # Strictly validate against path traversal while allowing `..` in legitimate filenames.
    # by ensuring the normalized path exactly matches the raw path 
    # (since normpath resolves syntactic `..` directories but ignores filename `..`)
    if ".." in file_path.replace(os.path.basename(file_path), ""):
        # If `..` exists in the parent directory path, it's a traversal attempt
        raise HTTPException(status_code=400, detail="Path traversal not allowed")

    # Run analysis: Load audio ONCE at 22050 Hz and share it for features, genre, mood
    # SOC2 Rule 2: decoding is local.
    try:
        import librosa
        # Load 120s once for standard feature analysis.
        # Get full file duration via header info for correct structural markers.
        full_dur = librosa.get_duration(path=file_path)
        y_22k, sr_22k = librosa.load(file_path, sr=22050, mono=True, duration=120.0)
        
        features = extract_features(file_path, y=y_22k, sr=sr_22k, true_duration_ms=full_dur * 1000)
        
        # We use the trained AST Hierarchical Models for deep inference
        genre = infer_genre(file_path)
        
        mood = classify_mood(file_path, y=y_22k, sr=sr_22k)

        
        # CLAP embeddings require 48kHz, so we do one separate reload for that one
        embedding = generate_embedding(file_path)
        fingerprint = generate_fingerprint(file_path)

        return AnalyzeResponse(
            features=features,
            genre=genre,
            mood=mood,
            embedding=embedding,
            fingerprint=fingerprint,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Analysis error: {str(e)}")


@app.post("/stems")
async def start_stem_separation(
    req: StemRequest,
    background_tasks: BackgroundTasks,
    _: str = Security(require_api_key),
):
    """
    Start async stem separation. Returns job_id for polling.
    SOC2 Rule 2: stems written to local output_dir only.
    """
    file_path = os.path.normpath(req.file_path)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")

    job_id = separate_stems_async(file_path, req.output_dir)
    return {"job_id": job_id, "status": "queued"}


@app.get("/stems/{job_id}")
async def get_stem_status(
    job_id: str,
    _: str = Security(require_api_key),
):
    """Poll stem separation job status."""
    job = get_job_status(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    return job


# ─── Entry Point ─────────────────────────────────────────────────

if __name__ == "__main__":
    # SOC2 Rule 2: bind to loopback ONLY
    uvicorn.run(
        "main:app",
        host="127.0.0.1",
        port=7433,
        log_level="info",
        access_log=False,   # Avoid logging file paths in access logs
    )
